# AUTO-GENERATED from ChallengeScreen.cpp gChallengeDefs by tools (port). Do not edit by hand.
class_name ChallengeDefs

const MODE := 0
const IMAGE := 1
const PAGE := 2
const ROW := 3
const COL := 4
const NAME := 5
const HAS_TROPHY := 6

## [challenge_mode, challenge_icon_index, page, row, col, name, has_trophy]
const DEFS := [
	[PvZ.GAMEMODE_SURVIVAL_NORMAL_STAGE_1, 0, PvZ.CHALLENGE_PAGE_SURVIVAL, 0, 0, "[SURVIVAL_DAY_NORMAL]", true],
	[PvZ.GAMEMODE_SURVIVAL_NORMAL_STAGE_2, 1, PvZ.CHALLENGE_PAGE_SURVIVAL, 1, 0, "[SURVIVAL_NIGHT_NORMAL]", true],
	[PvZ.GAMEMODE_SURVIVAL_NORMAL_STAGE_3, 2, PvZ.CHALLENGE_PAGE_SURVIVAL, 2, 0, "[SURVIVAL_POOL_NORMAL]", true],
	[PvZ.GAMEMODE_SURVIVAL_NORMAL_STAGE_4, 3, PvZ.CHALLENGE_PAGE_SURVIVAL, 3, 0, "[SURVIVAL_FOG_NORMAL]", true],
	[PvZ.GAMEMODE_SURVIVAL_NORMAL_STAGE_5, 4, PvZ.CHALLENGE_PAGE_SURVIVAL, 4, 0, "[SURVIVAL_ROOF_NORMAL]", true],
	[PvZ.GAMEMODE_SURVIVAL_HARD_STAGE_1, 5, PvZ.CHALLENGE_PAGE_SURVIVAL, 0, 1, "[SURVIVAL_DAY_HARD]", true],
	[PvZ.GAMEMODE_SURVIVAL_HARD_STAGE_2, 6, PvZ.CHALLENGE_PAGE_SURVIVAL, 1, 1, "[SURVIVAL_NIGHT_HARD]", true],
	[PvZ.GAMEMODE_SURVIVAL_HARD_STAGE_3, 7, PvZ.CHALLENGE_PAGE_SURVIVAL, 2, 1, "[SURVIVAL_POOL_HARD]", true],
	[PvZ.GAMEMODE_SURVIVAL_HARD_STAGE_4, 8, PvZ.CHALLENGE_PAGE_SURVIVAL, 3, 1, "[SURVIVAL_FOG_HARD]", true],
	[PvZ.GAMEMODE_SURVIVAL_HARD_STAGE_5, 9, PvZ.CHALLENGE_PAGE_SURVIVAL, 4, 1, "[SURVIVAL_ROOF_HARD]", true],
	[PvZ.GAMEMODE_SURVIVAL_ENDLESS_STAGE_1, 10, PvZ.CHALLENGE_PAGE_LIMBO, 0, 3, "[SURVIVAL_DAY_ENDLESS]", false],
	[PvZ.GAMEMODE_SURVIVAL_ENDLESS_STAGE_2, 10, PvZ.CHALLENGE_PAGE_LIMBO, 1, 3, "[SURVIVAL_NIGHT_ENDLESS]", false],
	[PvZ.GAMEMODE_SURVIVAL_ENDLESS_STAGE_3, 10, PvZ.CHALLENGE_PAGE_SURVIVAL, 2, 2, "[SURVIVAL_POOL_ENDLESS]", false],
	[PvZ.GAMEMODE_SURVIVAL_ENDLESS_STAGE_4, 10, PvZ.CHALLENGE_PAGE_LIMBO, 2, 3, "[SURVIVAL_FOG_ENDLESS]", false],
	[PvZ.GAMEMODE_SURVIVAL_ENDLESS_STAGE_5, 10, PvZ.CHALLENGE_PAGE_LIMBO, 3, 3, "[SURVIVAL_ROOF_ENDLESS]", false],
	[PvZ.GAMEMODE_CHALLENGE_WAR_AND_PEAS, 0, PvZ.CHALLENGE_PAGE_CHALLENGE, 0, 0, "[WAR_AND_PEAS]", true],
	[PvZ.GAMEMODE_CHALLENGE_WALLNUT_BOWLING, 6, PvZ.CHALLENGE_PAGE_CHALLENGE, 1, 0, "[WALL_NUT_BOWLING]", true],
	[PvZ.GAMEMODE_CHALLENGE_SLOT_MACHINE, 2, PvZ.CHALLENGE_PAGE_CHALLENGE, 2, 0, "[SLOT_MACHINE]", true],
	[PvZ.GAMEMODE_CHALLENGE_RAINING_SEEDS, 3, PvZ.CHALLENGE_PAGE_CHALLENGE, 3, 0, "[ITS_RAINING_SEEDS]", true],
	[PvZ.GAMEMODE_CHALLENGE_BEGHOULED, 1, PvZ.CHALLENGE_PAGE_CHALLENGE, 4, 0, "[BEGHOULED]", true],
	[PvZ.GAMEMODE_CHALLENGE_INVISIGHOUL, 8, PvZ.CHALLENGE_PAGE_CHALLENGE, 0, 1, "[INVISIGHOUL]", true],
	[PvZ.GAMEMODE_CHALLENGE_SEEING_STARS, 5, PvZ.CHALLENGE_PAGE_CHALLENGE, 1, 1, "[SEEING_STARS]", true],
	[PvZ.GAMEMODE_CHALLENGE_ZOMBIQUARIUM, 7, PvZ.CHALLENGE_PAGE_CHALLENGE, 2, 1, "[ZOMBIQUARIUM]", true],
	[PvZ.GAMEMODE_CHALLENGE_BEGHOULED_TWIST, 20, PvZ.CHALLENGE_PAGE_CHALLENGE, 3, 1, "[BEGHOULED_TWIST]", true],
	[PvZ.GAMEMODE_CHALLENGE_LITTLE_TROUBLE, 12, PvZ.CHALLENGE_PAGE_CHALLENGE, 4, 1, "[LITTLE_TROUBLE]", true],
	[PvZ.GAMEMODE_CHALLENGE_PORTAL_COMBAT, 15, PvZ.CHALLENGE_PAGE_CHALLENGE, 0, 2, "[PORTAL_COMBAT]", true],
	[PvZ.GAMEMODE_CHALLENGE_COLUMN, 4, PvZ.CHALLENGE_PAGE_CHALLENGE, 1, 2, "[COLUMN_AS_YOU_SEE_EM]", true],
	[PvZ.GAMEMODE_CHALLENGE_BOBSLED_BONANZA, 17, PvZ.CHALLENGE_PAGE_CHALLENGE, 2, 2, "[BOBSLED_BONANZA]", true],
	[PvZ.GAMEMODE_CHALLENGE_SPEED, 18, PvZ.CHALLENGE_PAGE_CHALLENGE, 3, 2, "[ZOMBIES_ON_SPEED]", true],
	[PvZ.GAMEMODE_CHALLENGE_WHACK_A_ZOMBIE, 16, PvZ.CHALLENGE_PAGE_CHALLENGE, 4, 2, "[WHACK_A_ZOMBIE]", true],
	[PvZ.GAMEMODE_CHALLENGE_LAST_STAND, 21, PvZ.CHALLENGE_PAGE_CHALLENGE, 0, 3, "[LAST_STAND]", true],
	[PvZ.GAMEMODE_CHALLENGE_WAR_AND_PEAS_2, 0, PvZ.CHALLENGE_PAGE_CHALLENGE, 1, 3, "[WAR_AND_PEAS_2]", true],
	[PvZ.GAMEMODE_CHALLENGE_WALLNUT_BOWLING_2, 6, PvZ.CHALLENGE_PAGE_CHALLENGE, 2, 3, "[WALL_NUT_BOWLING_EXTREME]", true],
	[PvZ.GAMEMODE_CHALLENGE_POGO_PARTY, 14, PvZ.CHALLENGE_PAGE_CHALLENGE, 3, 3, "[POGO_PARTY]", true],
	[PvZ.GAMEMODE_CHALLENGE_FINAL_BOSS, 19, PvZ.CHALLENGE_PAGE_CHALLENGE, 4, 3, "[FINAL_BOSS]", true],
	[PvZ.GAMEMODE_CHALLENGE_ART_CHALLENGE_WALLNUT, 0, PvZ.CHALLENGE_PAGE_LIMBO, 0, 0, "[ART_CHALLENGE_WALL_NUT]", false],
	[PvZ.GAMEMODE_CHALLENGE_SUNNY_DAY, 1, PvZ.CHALLENGE_PAGE_LIMBO, 1, 0, "[SUNNY_DAY]", false],
	[PvZ.GAMEMODE_CHALLENGE_RESODDED, 2, PvZ.CHALLENGE_PAGE_LIMBO, 2, 0, "[UNSODDED]", false],
	[PvZ.GAMEMODE_CHALLENGE_BIG_TIME, 3, PvZ.CHALLENGE_PAGE_LIMBO, 3, 0, "[BIG_TIME]", false],
	[PvZ.GAMEMODE_CHALLENGE_ART_CHALLENGE_SUNFLOWER, 4, PvZ.CHALLENGE_PAGE_LIMBO, 4, 0, "[ART_CHALLENGE_SUNFLOWER]", false],
	[PvZ.GAMEMODE_CHALLENGE_AIR_RAID, 5, PvZ.CHALLENGE_PAGE_LIMBO, 0, 1, "[AIR_RAID]", false],
	[PvZ.GAMEMODE_CHALLENGE_ICE, 6, PvZ.CHALLENGE_PAGE_LIMBO, 1, 1, "[ICE_LEVEL]", false],
	[PvZ.GAMEMODE_CHALLENGE_ZEN_GARDEN, 7, PvZ.CHALLENGE_PAGE_LIMBO, 2, 1, "[ZEN_GARDEN]", false],
	[PvZ.GAMEMODE_CHALLENGE_HIGH_GRAVITY, 8, PvZ.CHALLENGE_PAGE_LIMBO, 3, 1, "[HIGH_GRAVITY]", false],
	[PvZ.GAMEMODE_CHALLENGE_GRAVE_DANGER, 11, PvZ.CHALLENGE_PAGE_LIMBO, 4, 1, "[GRAVE_DANGER]", false],
	[PvZ.GAMEMODE_CHALLENGE_SHOVEL, 10, PvZ.CHALLENGE_PAGE_LIMBO, 0, 2, "[CAN_YOU_DIG_IT]", false],
	[PvZ.GAMEMODE_CHALLENGE_STORMY_NIGHT, 13, PvZ.CHALLENGE_PAGE_LIMBO, 1, 2, "[DARK_STORMY_NIGHT]", false],
	[PvZ.GAMEMODE_CHALLENGE_BUNGEE_BLITZ, 9, PvZ.CHALLENGE_PAGE_LIMBO, 2, 2, "[BUNGEE_BLITZ]", false],
	[PvZ.GAMEMODE_CHALLENGE_SQUIRREL, 10, PvZ.CHALLENGE_PAGE_LIMBO, 0, 4, "Squirrel", false],
	[PvZ.GAMEMODE_TREE_OF_WISDOM, 10, PvZ.CHALLENGE_PAGE_LIMBO, 4, 2, "Tree Of Wisdom", false],
	[PvZ.GAMEMODE_SCARY_POTTER_1, 10, PvZ.CHALLENGE_PAGE_PUZZLE, 0, 0, "[SCARY_POTTER_1]", true],
	[PvZ.GAMEMODE_SCARY_POTTER_2, 10, PvZ.CHALLENGE_PAGE_PUZZLE, 1, 0, "[SCARY_POTTER_2]", true],
	[PvZ.GAMEMODE_SCARY_POTTER_3, 10, PvZ.CHALLENGE_PAGE_PUZZLE, 2, 0, "[SCARY_POTTER_3]", true],
	[PvZ.GAMEMODE_SCARY_POTTER_4, 10, PvZ.CHALLENGE_PAGE_PUZZLE, 3, 0, "[SCARY_POTTER_4]", true],
	[PvZ.GAMEMODE_SCARY_POTTER_5, 10, PvZ.CHALLENGE_PAGE_PUZZLE, 4, 0, "[SCARY_POTTER_5]", true],
	[PvZ.GAMEMODE_SCARY_POTTER_6, 10, PvZ.CHALLENGE_PAGE_PUZZLE, 0, 1, "[SCARY_POTTER_6]", true],
	[PvZ.GAMEMODE_SCARY_POTTER_7, 10, PvZ.CHALLENGE_PAGE_PUZZLE, 1, 1, "[SCARY_POTTER_7]", true],
	[PvZ.GAMEMODE_SCARY_POTTER_8, 10, PvZ.CHALLENGE_PAGE_PUZZLE, 2, 1, "[SCARY_POTTER_8]", true],
	[PvZ.GAMEMODE_SCARY_POTTER_9, 10, PvZ.CHALLENGE_PAGE_PUZZLE, 3, 1, "[SCARY_POTTER_9]", true],
	[PvZ.GAMEMODE_SCARY_POTTER_ENDLESS, 10, PvZ.CHALLENGE_PAGE_PUZZLE, 4, 1, "[SCARY_POTTER_ENDLESS]", false],
	[PvZ.GAMEMODE_PUZZLE_I_ZOMBIE_1, 11, PvZ.CHALLENGE_PAGE_PUZZLE, 0, 2, "[I_ZOMBIE_1]", true],
	[PvZ.GAMEMODE_PUZZLE_I_ZOMBIE_2, 11, PvZ.CHALLENGE_PAGE_PUZZLE, 1, 2, "[I_ZOMBIE_2]", true],
	[PvZ.GAMEMODE_PUZZLE_I_ZOMBIE_3, 11, PvZ.CHALLENGE_PAGE_PUZZLE, 2, 2, "[I_ZOMBIE_3]", true],
	[PvZ.GAMEMODE_PUZZLE_I_ZOMBIE_4, 11, PvZ.CHALLENGE_PAGE_PUZZLE, 3, 2, "[I_ZOMBIE_4]", true],
	[PvZ.GAMEMODE_PUZZLE_I_ZOMBIE_5, 11, PvZ.CHALLENGE_PAGE_PUZZLE, 4, 2, "[I_ZOMBIE_5]", true],
	[PvZ.GAMEMODE_PUZZLE_I_ZOMBIE_6, 11, PvZ.CHALLENGE_PAGE_PUZZLE, 0, 3, "[I_ZOMBIE_6]", true],
	[PvZ.GAMEMODE_PUZZLE_I_ZOMBIE_7, 11, PvZ.CHALLENGE_PAGE_PUZZLE, 1, 3, "[I_ZOMBIE_7]", true],
	[PvZ.GAMEMODE_PUZZLE_I_ZOMBIE_8, 11, PvZ.CHALLENGE_PAGE_PUZZLE, 2, 3, "[I_ZOMBIE_8]", true],
	[PvZ.GAMEMODE_PUZZLE_I_ZOMBIE_9, 11, PvZ.CHALLENGE_PAGE_PUZZLE, 3, 3, "[I_ZOMBIE_9]", true],
	[PvZ.GAMEMODE_PUZZLE_I_ZOMBIE_ENDLESS, 11, PvZ.CHALLENGE_PAGE_PUZZLE, 4, 3, "[I_ZOMBIE_ENDLESS]", false],
	[PvZ.GAMEMODE_UPSELL, 10, PvZ.CHALLENGE_PAGE_LIMBO, 4, 3, "[UPSELL]", false],
	[PvZ.GAMEMODE_INTRO, 10, PvZ.CHALLENGE_PAGE_LIMBO, 3, 2, "[INTRO]", false],
]

static func get_def(index: int) -> Array:
	return DEFS[index]
