# AUTO-GENERATED by tools/gen_type_tables.py
class_name ParticleTypes

## Index = PvZ.PARTICLE_* value.
static var files: PackedStringArray = PackedStringArray([
	"particles/MelonImpact.xml",  # PARTICLE_MELONSPLASH
	"particles/WinterMelonImpact.xml",  # PARTICLE_WINTERMELON
	"particles/FumeCloud.xml",  # PARTICLE_FUMECLOUD
	"particles/PopcornSplash.xml",  # PARTICLE_POPCORNSPLASH
	"particles/Powie.xml",  # PARTICLE_POWIE
	"particles/JackExplode.xml",  # PARTICLE_JACKEXPLODE
	"particles/ZombieHead.xml",  # PARTICLE_ZOMBIE_HEAD
	"particles/ZombieArm.xml",  # PARTICLE_ZOMBIE_ARM
	"particles/ZombieTrafficCone.xml",  # PARTICLE_ZOMBIE_TRAFFIC_CONE
	"particles/ZombiePail.xml",  # PARTICLE_ZOMBIE_PAIL
	"particles/ZombieHelmet.xml",  # PARTICLE_ZOMBIE_HELMET
	"particles/ZombieFlag.xml",  # PARTICLE_ZOMBIE_FLAG
	"particles/ZombieDoor.xml",  # PARTICLE_ZOMBIE_DOOR
	"particles/ZombieNewspaper.xml",  # PARTICLE_ZOMBIE_NEWSPAPER
	"particles/ZombieHeadLight.xml",  # PARTICLE_ZOMBIE_HEADLIGHT
	"particles/Pow.xml",  # PARTICLE_POW
	"particles/ZombiePogo.xml",  # PARTICLE_ZOMBIE_POGO
	"particles/ZombieNewspaperHead.xml",  # PARTICLE_ZOMBIE_NEWSPAPER_HEAD
	"particles/ZombieBalloonHead.xml",  # PARTICLE_ZOMBIE_BALLOON_HEAD
	"particles/SodRoll.xml",  # PARTICLE_SOD_ROLL
	"particles/GraveStoneRise.xml",  # PARTICLE_GRAVE_STONE_RISE
	"particles/Planting.xml",  # PARTICLE_PLANTING
	"particles/PlantingPool.xml",  # PARTICLE_PLANTING_POOL
	"particles/ZombieRise.xml",  # PARTICLE_ZOMBIE_RISE
	"particles/GraveBuster.xml",  # PARTICLE_GRAVE_BUSTER
	"particles/GraveBusterDie.xml",  # PARTICLE_GRAVE_BUSTER_DIE
	"particles/PoolSplash.xml",  # PARTICLE_POOL_SPLASH
	"particles/IceSparkle.xml",  # PARTICLE_ICE_SPARKLE
	"particles/SeedPacket.xml",  # PARTICLE_SEED_PACKET
	"particles/TallNutBlock.xml",  # PARTICLE_TALL_NUT_BLOCK
	"particles/Doom.xml",  # PARTICLE_DOOM
	"particles/DiggerRise.xml",  # PARTICLE_DIGGER_RISE
	"particles/DiggerTunnel.xml",  # PARTICLE_DIGGER_TUNNEL
	"particles/DancerRise.xml",  # PARTICLE_DANCER_RISE
	"particles/PoolSparkly.xml",  # PARTICLE_POOL_SPARKLY
	"particles/WallnutEatSmall.xml",  # PARTICLE_WALLNUT_EAT_SMALL
	"particles/WallnutEatLarge.xml",  # PARTICLE_WALLNUT_EAT_LARGE
	"particles/PeaSplat.xml",  # PARTICLE_PEA_SPLAT
	"particles/ButterSplat.xml",  # PARTICLE_BUTTER_SPLAT
	"particles/CabbageSplat.xml",  # PARTICLE_CABBAGE_SPLAT
	"particles/PuffSplat.xml",  # PARTICLE_PUFF_SPLAT
	"particles/StarSplat.xml",  # PARTICLE_STAR_SPLAT
	"particles/IceTrap.xml",  # PARTICLE_ICE_TRAP
	"particles/SnowPeaSplat.xml",  # PARTICLE_SNOWPEA_SPLAT
	"particles/SnowPeaPuff.xml",  # PARTICLE_SNOWPEA_PUFF
	"particles/SnowPeaTrail.xml",  # PARTICLE_SNOWPEA_TRAIL
	"particles/LanternShine.xml",  # PARTICLE_LANTERN_SHINE
	"particles/Award.xml",  # PARTICLE_SEED_PACKET_PICKUP
	"particles/PotatoMine.xml",  # PARTICLE_POTATO_MINE
	"particles/PotatoMineRise.xml",  # PARTICLE_POTATO_MINE_RISE
	"particles/PuffShroomTrail.xml",  # PARTICLE_PUFFSHROOM_TRAIL
	"particles/PuffShroomMuzzle.xml",  # PARTICLE_PUFFSHROOM_MUZZLE
	"particles/SeedPacketFlash.xml",  # PARTICLE_SEED_PACKET_FLASH
	"particles/WhackAZombieRise.xml",  # PARTICLE_WHACK_A_ZOMBIE_RISE
	"particles/ZombieLadder.xml",  # PARTICLE_ZOMBIE_LADDER
	"particles/UmbrellaReflect.xml",  # PARTICLE_UMBRELLA_REFLECT
	"particles/SeedPacketPick.xml",  # PARTICLE_SEED_PACKET_PICK
	"particles/IceTrapZombie.xml",  # PARTICLE_ICE_TRAP_ZOMBIE
	"particles/IceTrapRelease.xml",  # PARTICLE_ICE_TRAP_RELEASE
	"particles/ZamboniSmoke.xml",  # PARTICLE_ZAMBONI_SMOKE
	"particles/GloomCloud.xml",  # PARTICLE_GLOOMCLOUD
	"particles/ZombiePogoHead.xml",  # PARTICLE_ZOMBIE_POGO_HEAD
	"particles/ZamboniTire.xml",  # PARTICLE_ZAMBONI_TIRE
	"particles/ZamboniExplosion.xml",  # PARTICLE_ZAMBONI_EXPLOSION
	"particles/ZamboniExplosion2.xml",  # PARTICLE_ZAMBONI_EXPLOSION2
	"particles/CatapultExplosion.xml",  # PARTICLE_CATAPULT_EXPLOSION
	"particles/MowerCloud.xml",  # PARTICLE_MOWER_CLOUD
	"particles/BossIceBallTrail.xml",  # PARTICLE_BOSS_ICE_BALL
	"particles/BlastMark.xml",  # PARTICLE_BLASTMARK
	"particles/CoinPickupArrow.xml",  # PARTICLE_COIN_PICKUP_ARROW
	"particles/PresentPickup.xml",  # PARTICLE_PRESENT_PICKUP
	"particles/ImitaterMorph.xml",  # PARTICLE_IMITATER_MORPH
	"particles/MoweredZombieHead.xml",  # PARTICLE_MOWERED_ZOMBIE_HEAD
	"particles/MoweredZombieArm.xml",  # PARTICLE_MOWERED_ZOMBIE_ARM
	"particles/ZombieHeadPool.xml",  # PARTICLE_ZOMBIE_HEAD_POOL
	"particles/Zombie_boss_fireball.xml",  # PARTICLE_ZOMBIE_BOSS_FIREBALL
	"particles/FireballDeath.xml",  # PARTICLE_FIREBALL_DEATH
	"particles/IceballDeath.xml",  # PARTICLE_ICEBALL_DEATH
	"particles/Iceball_Trail.xml",  # PARTICLE_ICEBALL_TRAIL
	"particles/Fireball_Trail.xml",  # PARTICLE_FIREBALL_TRAIL
	"particles/BossExplosion.xml",  # PARTICLE_BOSS_EXPLOSION
	"particles/ScreenFlash.xml",  # PARTICLE_SCREEN_FLASH
	"particles/TrophySparkle.xml",  # PARTICLE_TROPHY_SPARKLE
	"particles/PortalCircle.xml",  # PARTICLE_PORTAL_CIRCLE
	"particles/PortalSquare.xml",  # PARTICLE_PORTAL_SQUARE
	"particles/PottedPlantGlow.xml",  # PARTICLE_POTTED_PLANT_GLOW
	"particles/PottedWaterPlantGlow.xml",  # PARTICLE_POTTED_WATER_PLANT_GLOW
	"particles/PottedZenGlow.xml",  # PARTICLE_POTTED_ZEN_GLOW
	"particles/MindControl.xml",  # PARTICLE_MIND_CONTROL
	"particles/VaseShatter.xml",  # PARTICLE_VASE_SHATTER
	"particles/VaseShatterLeaf.xml",  # PARTICLE_VASE_SHATTER_LEAF
	"particles/VaseShatterZombie.xml",  # PARTICLE_VASE_SHATTER_ZOMBIE
	"particles/AwardPickupArrow.xml",  # PARTICLE_AWARD_PICKUP_ARROW
	"particles/Zombie_seaweed.xml",  # PARTICLE_ZOMBIE_SEAWEED
	"particles/ZombieMustache.xml",  # PARTICLE_ZOMBIE_MUSTACHE
	"particles/ZombieFutureGlasses.xml",  # PARTICLE_ZOMBIE_SUNGLASS
	"particles/Pinata.xml",  # PARTICLE_ZOMBIE_PINATA
	"particles/Dust_Squash.xml",  # PARTICLE_DUST_SQUASH
	"particles/Dust_Foot.xml",  # PARTICLE_DUST_FOOT
	"particles/Daisy.xml",  # PARTICLE_ZOMBIE_DAISIES
	"particles/Credits_Strobe.xml",  # PARTICLE_CREDIT_STROBE
	"particles/Credits_RaysWipe.xml",  # PARTICLE_CREDITS_RAYSWIPE
	"particles/Credits_ZombieHeadWipe.xml",  # PARTICLE_CREDITS_ZOMBIEHEADWIPE
	"particles/Starburst.xml",  # PARTICLE_STARBURST
	"particles/Credits_fog.xml",  # PARTICLE_CREDITS_FOG
	"particles/UpsellArrow.xml",  # PARTICLE_PERSENT_PICK_UP_ARROW
])
static var _defs: Dictionary = {}

static func get_def(effect: int) -> Defs.ParticleDef:
	if not _defs.has(effect):
		_defs[effect] = Defs.load_particle(files[effect])
	return _defs[effect]

static func register(path: String) -> int:
	files.append(path)
	return files.size() - 1
