# AUTO-GENERATED by tools/gen_type_tables.py
class_name ReanimTypes

## Index = PvZ.REANIM_* value. Custom reanims can be appended at runtime with register().
static var files: PackedStringArray = PackedStringArray([
	"reanim/LoadBar_sprout.reanim",  # REANIM_LOADBAR_SPROUT
	"reanim/LoadBar_Zombiehead.reanim",  # REANIM_LOADBAR_ZOMBIEHEAD
	"reanim/SodRoll.reanim",  # REANIM_SODROLL
	"reanim/FinalWave.reanim",  # REANIM_FINAL_WAVE
	"reanim/PeaShooterSingle.reanim",  # REANIM_PEASHOOTER
	"reanim/Wallnut.reanim",  # REANIM_WALLNUT
	"reanim/Lilypad.reanim",  # REANIM_LILYPAD
	"reanim/SunFlower.reanim",  # REANIM_SUNFLOWER
	"reanim/LawnMower.reanim",  # REANIM_LAWNMOWER
	"reanim/StartReadySetPlant.reanim",  # REANIM_READYSETPLANT
	"reanim/CherryBomb.reanim",  # REANIM_CHERRYBOMB
	"reanim/Squash.reanim",  # REANIM_SQUASH
	"reanim/DoomShroom.reanim",  # REANIM_DOOMSHROOM
	"reanim/SnowPea.reanim",  # REANIM_SNOWPEA
	"reanim/PeaShooter.reanim",  # REANIM_REPEATER
	"reanim/SunShroom.reanim",  # REANIM_SUNSHROOM
	"reanim/Tallnut.reanim",  # REANIM_TALLNUT
	"reanim/Fumeshroom.reanim",  # REANIM_FUMESHROOM
	"reanim/Puffshroom.reanim",  # REANIM_PUFFSHROOM
	"reanim/Hypnoshroom.reanim",  # REANIM_HYPNOSHROOM
	"reanim/Chomper.reanim",  # REANIM_CHOMPER
	"reanim/Zombie.reanim",  # REANIM_ZOMBIE
	"reanim/Sun.reanim",  # REANIM_SUN
	"reanim/PotatoMine.reanim",  # REANIM_POTATOMINE
	"reanim/Caltrop.reanim",  # REANIM_SPIKEWEED
	"reanim/SpikeRock.reanim",  # REANIM_SPIKEROCK
	"reanim/ThreePeater.reanim",  # REANIM_THREEPEATER
	"reanim/Marigold.reanim",  # REANIM_MARIGOLD
	"reanim/IceShroom.reanim",  # REANIM_ICESHROOM
	"reanim/Zombie_football.reanim",  # REANIM_ZOMBIE_FOOTBALL
	"reanim/Zombie_paper.reanim",  # REANIM_ZOMBIE_NEWSPAPER
	"reanim/Zombie_zamboni.reanim",  # REANIM_ZOMBIE_ZAMBONI
	"reanim/splash.reanim",  # REANIM_SPLASH
	"reanim/Jalapeno.reanim",  # REANIM_JALAPENO
	"reanim/fire.reanim",  # REANIM_JALAPENO_FIRE
	"reanim/Coin_silver.reanim",  # REANIM_COIN_SILVER
	"reanim/Zombie_charred.reanim",  # REANIM_ZOMBIE_CHARRED
	"reanim/Zombie_charred_imp.reanim",  # REANIM_ZOMBIE_CHARRED_IMP
	"reanim/Zombie_charred_digger.reanim",  # REANIM_ZOMBIE_CHARRED_DIGGER
	"reanim/Zombie_charred_zamboni.reanim",  # REANIM_ZOMBIE_CHARRED_ZAMBONI
	"reanim/Zombie_charred_catapult.reanim",  # REANIM_ZOMBIE_CHARRED_CATAPULT
	"reanim/Zombie_charred_gargantuar.reanim",  # REANIM_ZOMBIE_CHARRED_GARGANTUAR
	"reanim/ScaredyShroom.reanim",  # REANIM_SCRAREYSHROOM
	"reanim/Pumpkin.reanim",  # REANIM_PUMPKIN
	"reanim/Plantern.reanim",  # REANIM_PLANTERN
	"reanim/Torchwood.reanim",  # REANIM_TORCHWOOD
	"reanim/SplitPea.reanim",  # REANIM_SPLITPEA
	"reanim/SeaShroom.reanim",  # REANIM_SEASHROOM
	"reanim/Blover.reanim",  # REANIM_BLOVER
	"reanim/Pot.reanim",  # REANIM_FLOWER_POT
	"reanim/Cactus.reanim",  # REANIM_CACTUS
	"reanim/Zombie_disco.reanim",  # REANIM_DANCER
	"reanim/Tanglekelp.reanim",  # REANIM_TANGLEKELP
	"reanim/Starfruit.reanim",  # REANIM_STARFRUIT
	"reanim/Zombie_polevaulter.reanim",  # REANIM_POLEVAULTER
	"reanim/Zombie_balloon.reanim",  # REANIM_BALLOON
	"reanim/Zombie_gargantuar.reanim",  # REANIM_GARGANTUAR
	"reanim/Zombie_imp.reanim",  # REANIM_IMP
	"reanim/Zombie_digger.reanim",  # REANIM_DIGGER
	"reanim/Digger_rising_dirt.reanim",  # REANIM_DIGGER_DIRT
	"reanim/Zombie_dolphinrider.reanim",  # REANIM_ZOMBIE_DOLPHINRIDER
	"reanim/Zombie_pogo.reanim",  # REANIM_POGO
	"reanim/Zombie_backup.reanim",  # REANIM_BACKUP_DANCER
	"reanim/Zombie_bobsled.reanim",  # REANIM_BOBSLED
	"reanim/Zombie_jackbox.reanim",  # REANIM_JACKINTHEBOX
	"reanim/Zombie_snorkle.reanim",  # REANIM_SNORKEL
	"reanim/Zombie_bungi.reanim",  # REANIM_BUNGEE
	"reanim/Zombie_catapult.reanim",  # REANIM_CATAPULT
	"reanim/Zombie_ladder.reanim",  # REANIM_LADDER
	"reanim/Puff.reanim",  # REANIM_PUFF
	"reanim/Z.reanim",  # REANIM_SLEEPING
	"reanim/Gravebuster.reanim",  # REANIM_GRAVE_BUSTER
	"reanim/ZombiesWon.reanim",  # REANIM_ZOMBIES_WON
	"reanim/Magnetshroom.reanim",  # REANIM_MAGNETSHROOM
	"reanim/Zombie_boss.reanim",  # REANIM_BOSS
	"reanim/Cabbagepult.reanim",  # REANIM_CABBAGEPULT
	"reanim/Cornpult.reanim",  # REANIM_KERNELPULT
	"reanim/Melonpult.reanim",  # REANIM_MELONPULT
	"reanim/Coffeebean.reanim",  # REANIM_COFFEEBEAN
	"reanim/Umbrellaleaf.reanim",  # REANIM_UMBRELLALEAF
	"reanim/GatlingPea.reanim",  # REANIM_GATLINGPEA
	"reanim/Cattail.reanim",  # REANIM_CATTAIL
	"reanim/GloomShroom.reanim",  # REANIM_GLOOMSHROOM
	"reanim/Zombie_boss_iceball.reanim",  # REANIM_BOSS_ICEBALL
	"reanim/Zombie_boss_fireball.reanim",  # REANIM_BOSS_FIREBALL
	"reanim/CobCannon.reanim",  # REANIM_COBCANNON
	"reanim/Garlic.reanim",  # REANIM_GARLIC
	"reanim/GoldMagnet.reanim",  # REANIM_GOLD_MAGNET
	"reanim/WinterMelon.reanim",  # REANIM_WINTER_MELON
	"reanim/TwinSunflower.reanim",  # REANIM_TWIN_SUNFLOWER
	"reanim/PoolCleaner.reanim",  # REANIM_POOL_CLEANER
	"reanim/RoofCleaner.reanim",  # REANIM_ROOF_CLEANER
	"reanim/FirePea.reanim",  # REANIM_FIRE_PEA
	"reanim/Imitater.reanim",  # REANIM_IMITATER
	"reanim/Zombie_yeti.reanim",  # REANIM_YETI
	"reanim/Zombie_Boss_driver.reanim",  # REANIM_BOSS_DRIVER
	"reanim/LawnMoweredZombie.reanim",  # REANIM_LAWN_MOWERED_ZOMBIE
	"reanim/CrazyDave.reanim",  # REANIM_CRAZY_DAVE
	"reanim/TextFadeOn.reanim",  # REANIM_TEXT_FADE_ON
	"reanim/Hammer.reanim",  # REANIM_HAMMER
	"reanim/SlotMachine.reanim",  # REANIM_SLOT_MACHINE_HANDLE
	"reanim/Credits_Football.reanim",  # REANIM_CREDITS_FOOTBALL
	"reanim/Credits_Jackbox.reanim",  # REANIM_CREDITS_JACKBOX
	"reanim/SelectorScreen.reanim",  # REANIM_SELECTOR_SCREEN
	"reanim/Portal_Circle.reanim",  # REANIM_PORTAL_CIRCLE
	"reanim/Portal_Square.reanim",  # REANIM_PORTAL_SQUARE
	"reanim/ZenGarden_sprout.reanim",  # REANIM_ZENGARDEN_SPROUT
	"reanim/ZenGarden_wateringcan.reanim",  # REANIM_ZENGARDEN_WATERINGCAN
	"reanim/ZenGarden_fertilizer.reanim",  # REANIM_ZENGARDEN_FERTILIZER
	"reanim/ZenGarden_bugspray.reanim",  # REANIM_ZENGARDEN_BUGSPRAY
	"reanim/ZenGarden_phonograph.reanim",  # REANIM_ZENGARDEN_PHONOGRAPH
	"reanim/Diamond.reanim",  # REANIM_DIAMOND
	"reanim/Zombie_hand.reanim",  # REANIM_ZOMBIE_HAND
	"reanim/Stinky.reanim",  # REANIM_STINKY
	"reanim/Rake.reanim",  # REANIM_RAKE
	"reanim/Rain_circle.reanim",  # REANIM_RAIN_CIRCLE
	"reanim/Rain_splash.reanim",  # REANIM_RAIN_SPLASH
	"reanim/Zombie_surprise.reanim",  # REANIM_ZOMBIE_SURPRISE
	"reanim/Coin_gold.reanim",  # REANIM_COIN_GOLD
	"reanim/TreeOfWisdom.reanim",  # REANIM_TREEOFWISDOM
	"reanim/TreeOfWisdomClouds.reanim",  # REANIM_TREEOFWISDOM_CLOUDS
	"reanim/TreeFood.reanim",  # REANIM_TREEOFWISDOM_TREEFOOD
	"reanim/Credits_Main.reanim",  # REANIM_CREDITS_MAIN
	"reanim/Credits_Main2.reanim",  # REANIM_CREDITS_MAIN2
	"reanim/Credits_Main3.reanim",  # REANIM_CREDITS_MAIN3
	"reanim/Zombie_credits_dance.reanim",  # REANIM_ZOMBIE_CREDITS_DANCE
	"reanim/Credits_stage.reanim",  # REANIM_CREDITS_STAGE
	"reanim/Credits_BigBrain.reanim",  # REANIM_CREDITS_BIGBRAIN
	"reanim/Credits_Flower_petals.reanim",  # REANIM_CREDITS_FLOWER_PETALS
	"reanim/Credits_Infantry.reanim",  # REANIM_CREDITS_INFANTRY
	"reanim/Credits_Throat.reanim",  # REANIM_CREDITS_THROAT
	"reanim/Credits_CrazyDave.reanim",  # REANIM_CREDITS_CRAZYDAVE
	"reanim/Credits_Bossdance.reanim",  # REANIM_CREDITS_BOSSDANCE
	"reanim/Zombie_Credits_Screendoor.reanim",  # REANIM_ZOMBIE_CREDITS_SCREEN_DOOR
	"reanim/Zombie_Credits_Conehead.reanim",  # REANIM_ZOMBIE_CREDITS_CONEHEAD
	"reanim/Credits_ZombieArmy1.reanim",  # REANIM_CREDITS_ZOMBIEARMY1
	"reanim/Credits_ZombieArmy2.reanim",  # REANIM_CREDITS_ZOMBIEARMY2
	"reanim/Credits_Tombstones.reanim",  # REANIM_CREDITS_TOMBSTONES
	"reanim/Credits_SolarPower.reanim",  # REANIM_CREDITS_SOLARPOWER
	"reanim/Credits_Anyhour.reanim",  # REANIM_CREDITS_ANYHOUR
	"reanim/Credits_WeAreTheUndead.reanim",  # REANIM_CREDITS_WEARETHEUNDEAD
	"reanim/Credits_DiscoLights.reanim",  # REANIM_CREDITS_DISCOLIGHTS
	"reanim/Zombie_FlagPole.reanim",  # REANIM_FLAG
	"reanim/bushes3.reanim",  # REANIM_BUSH3
	"reanim/bushes4.reanim",  # REANIM_BUSH4
	"reanim/bushes5.reanim",  # REANIM_BUSH5
	"reanim/Night_bushes3.reanim",  # REANIM_BUSH3_NIGHT
	"reanim/Night_bushes4.reanim",  # REANIM_BUSH4_NIGHT
	"reanim/Night_bushes5.reanim",  # REANIM_BUSH5_NIGHT
])
static var _defs: Dictionary = {}
static var _by_file: Dictionary = {}

static func get_def(type: int) -> Defs.ReanimDef:
	if not _defs.has(type):
		_defs[type] = Defs.load_reanim(files[type])
	return _defs[type]

static func type_from_file(path: String) -> int:
	if _by_file.is_empty():
		for i in files.size():
			_by_file[files[i].to_lower()] = i
	return _by_file.get(path.replace("\\", "/").to_lower(), -1)

## Registers a new reanim file (for custom content) and returns its type id.
static func register(path: String) -> int:
	var t := type_from_file(path)
	if t != -1:
		return t
	files.append(path)
	_by_file[path.to_lower()] = files.size() - 1
	return files.size() - 1
