"""Generates src/lawn/lawn_defs.gd (plant/zombie/projectile definitions, wave tables) from the decomp."""
import re, sys, pathlib
DECOMP = pathlib.Path(sys.argv[1] if len(sys.argv) > 1 else r"C:\Users\nik\Music\PVZ-QEWide-Tweaks-main")
ROOT = pathlib.Path(__file__).resolve().parent.parent
T = "\t"

def strip_ns(s):
    return re.sub(r"\w+::", "", s).strip()

plant = (DECOMP / "Lawn/Plant.cpp").read_text(encoding="latin1")
body = re.search(r"PlantDefinition gPlantDefs\[[^\]]*\]\s*=\s*\{(.*?)\n\};", plant, re.S).group(1)
plants = re.findall(r"\{\s*SeedType::(\w+),\s*nullptr,\s*ReanimationType::(\w+),\s*(\d+),\s*(\d+),\s*(\d+),\s*PlantSubClass::(\w+),\s*(\d+),\s*_S\(\"(\w+)\"\)\s*\}", body)

zombie = (DECOMP / "Lawn/Zombie.cpp").read_text(encoding="latin1")
zbody = re.search(r"ZombieDefinition gZombieDefs\[[^\]]*\]\s*=\s*\{(.*?)\n\};", zombie, re.S).group(1)
zombies = re.findall(r"\{\s*(\w+),\s*(\w+),\s*(\d+),\s*(\d+),\s*(\d+),\s*(\d+),\s*_S\(\"(\w+)\"\)\s*\}", zbody)

proj = (DECOMP / "Lawn/Projectile.cpp").read_text(encoding="latin1")
pbody = re.search(r"ProjectileDefinition gProjectileDefinition\[\]\s*=\s*\{(.*?)\n\};", proj, re.S).group(1)
projs = re.findall(r"\{\s*ProjectileType::(\w+),\s*(\d+),\s*(\d+),\s*_S\(\"(\w+)\"\)\s*\}", pbody)

chal = (DECOMP / "Lawn/Challenge.cpp").read_text(encoding="latin1")
waves = [int(x) for x in re.findall(r"\d+", re.search(r"int gZombieWaves\[NUM_LEVELS\]\s*=\s*\{(.*?)\};", chal, re.S).group(1))]
abody = re.search(r"ZombieAllowedLevels gZombieAllowedLevels\[[^\]]*\]\s*=\s*\{(.*?)\n\};", chal, re.S).group(1)
allowed = re.findall(r"\{\s*(ZOMBIE_\w+),\s*\{([^}]*)\}\s*\}", abody)

out = ["# AUTO-GENERATED by tools/gen_defs.py from the decomp tables. Do not edit by hand.", "class_name LawnDefs", ""]
out.append("## [seed_type, reanim_type, packet_index, cost, refresh_time, subclass, launch_rate, name]")
out.append("static var PLANT_DEFS := [")
for p in plants:
    out.append(T + "[PvZ.%s, PvZ.%s, %s, %s, %s, PvZ.%s, %s, \"%s\"]," % p)
out.append("]")
out.append("")
out.append("## [zombie_type, reanim_type, value, starting_level, first_allowed_wave, pick_weight, name]")
out.append("static var ZOMBIE_DEFS := [")
for z in zombies:
    out.append(T + "[PvZ.%s, PvZ.%s, %s, %s, %s, %s, \"%s\"]," % z)
out.append("]")
out.append("")
out.append("## [projectile_type, image_row, damage, name]")
out.append("static var PROJECTILE_DEFS := [")
for p in projs:
    out.append(T + "[PvZ.%s, %s, %s, \"%s\"]," % p)
out.append("]")
out.append("")
out.append("static var ZOMBIE_WAVES := %s" % waves)
out.append("")
out.append("## zombie type -> 50 flags")
out.append("static var ZOMBIE_ALLOWED_LEVELS := {")
for name, vals in allowed:
    nums = [int(v) for v in re.findall(r"\d+", vals)]
    nums += [0] * (50 - len(nums))  # C++ `{}` / `{ 0 }` zero-fills all NUM_LEVELS entries
    out.append(T + "PvZ.%s: %s," % (name, nums))
out.append("}")
out.append("")
(ROOT / "src/lawn").mkdir(parents=True, exist_ok=True)
(ROOT / "src/lawn/lawn_defs.gd").write_text("\n".join(out) + "\n", encoding="utf-8")
print(len(plants), "plants", len(zombies), "zombies", len(projs), "projectiles", len(waves), "waves", len(allowed), "allowed")
