"""Generates src/core/pvz.gd (class PvZ) from the decomp's enum headers + GameConstants.h."""
import re, sys, pathlib

DECOMP = pathlib.Path(sys.argv[1] if len(sys.argv) > 1 else r"C:\Users\nik\Music\PVZ-QEWide-Tweaks-main")
OUT = pathlib.Path(__file__).resolve().parent.parent / "src" / "core" / "pvz.gd"

HEADERS = ["ConstEnums.h", "Lawn/Plant.h", "Lawn/Zombie.h", "Lawn/Challenge.h", "Lawn/System/Music.h",
           "Lawn/Widget/CreditScreen.h", "Lawn/Widget/GameSelector.h", "Lawn/Widget/TitleScreen.h",
           "Sexy.TodLib/TodFoley.h", "Sexy.TodLib/Trail.h", "Sexy.TodLib/FilterEffect.h"]
SKIP = {"FoleyFlags", "TrailFlags", "TrailTracks", "ParticleFlags"}

src = ""
for h in HEADERS:
    src += "\n" + (DECOMP / h).read_text(encoding="latin1")
src = re.sub(r"//.*", "", src)

out = ["# AUTO-GENERATED by tools/gen_enums.py from the decomp enum headers / GameConstants.h. Do not edit by hand.",
       "class_name PvZ", ""]
seen = {}
for m in re.finditer(r"enum\s+(\w+)\s*\{(.*?)\};", src, re.S):
    name, body = m.group(1), m.group(2)
    if name in SKIP:
        continue
    body = re.sub(r"ENUM_VALUE\((\w+),\s*([^)]+)\)", r"\1 = \2,", body)
    body = re.sub(r"ENUM_AUTO_VALUE\((\w+)\)", r"\1,", body)
    cur = -1
    lines = []
    for item in [x.strip() for x in body.split(",")]:
        if not item:
            continue
        if "=" in item:
            k, v = [x.strip() for x in item.split("=", 1)]
            cur = int(eval(v, {}, dict(seen)))
        else:
            k = item
            cur += 1
        if k in seen:
            if seen[k] != cur:
                print("COLLISION", name, k, seen[k], cur)
            continue
        seen[k] = cur
        lines.append("\t%s = %d," % (k, cur))
    if not lines:
        continue
    out.append("# " + name)
    out.append("enum {")
    out += lines
    out.append("}")
    out.append("")

gc = (DECOMP / "GameConstants.h").read_text(encoding="latin1")
gc = re.sub(r"//.*", "", gc)
count = 0
for m in re.finditer(r"const\s+(int|bool|double)\s+(\w+)\s*=\s*([^;]+);", gc):
    t, k, v = m.groups()
    out.append("const %s = %s" % (k, v.strip()))
    count += 1
OUT.write_text("\n".join(out) + "\n", encoding="utf-8")
print("wrote", OUT, len(seen), "enum values", count, "consts")
