"""Generates src/core/foley_table.gd from TodFoley.cpp."""
import re, sys, pathlib
DECOMP = pathlib.Path(sys.argv[1] if len(sys.argv) > 1 else r"C:\Users\nik\Music\PVZ-QEWide-Tweaks-main")
ROOT = pathlib.Path(__file__).resolve().parent.parent
src = (DECOMP / "Sexy.TodLib/TodFoley.cpp").read_text(encoding="latin1")
rows = re.findall(r"\{\s*FoleyType::(\w+),\s*(-?[\d.]+)f,\s*\{([^}]*)\},\s*(\d+)U\s*\}", src)
out = ["# AUTO-GENERATED by tools/gen_foley.py", "class_name FoleyTable", "",
       "## [pitch_range, [sound ids], flags] indexed by PvZ.FOLEY_*", "const ENTRIES := ["]
for name, pitch, sfx, flags in rows:
    ids = re.findall(r"Sexy::(SOUND_\w+)", sfx)
    out.append('\t[%s, [%s], %s],  # %s' % (pitch, ", ".join('"%s"' % i for i in ids), flags, name))
out.append("]")
(ROOT / "src/core/foley_table.gd").write_text("\n".join(out) + "\n", encoding="utf-8")
print(len(rows), "foley entries")
