"""Generates ReanimTypes / ParticleTypes tables from the decomp arrays (enum order -> file)."""
import re, sys, pathlib

DECOMP = pathlib.Path(sys.argv[1] if len(sys.argv) > 1 else r"C:\Users\nik\Music\PVZ-QEWide-Tweaks-main")
ROOT = pathlib.Path(__file__).resolve().parent.parent
BS = chr(92)


def clean(path):
    return path.replace(BS, "")


ra = (DECOMP / "Sexy.TodLib/Reanimator.cpp").read_text(encoding="latin1")
reanims = re.findall(r'\{\s*ReanimationType::(\w+),\s*"reanim([^"]+)",\s*(\d+)\s*\}', ra)
pa = (DECOMP / "Sexy.TodLib/TodParticle.cpp").read_text(encoding="latin1")
parts = re.findall(r'\{\s*ParticleEffect::(\w+),\s*"particles([^"]+)"\s*\}', pa)

TAB = "\t"
out = ["# AUTO-GENERATED by tools/gen_type_tables.py", "class_name ReanimTypes", "",
       "## Index = PvZ.REANIM_* value. Custom reanims can be appended at runtime with register().",
       "static var files: PackedStringArray = PackedStringArray(["]
for name, f, flags in reanims:
    out.append(TAB + '"reanim/' + clean(f) + '",  # ' + name)
out += [
    "])",
    "static var _defs: Dictionary = {}",
    "static var _by_file: Dictionary = {}",
    "",
    "static func get_def(type: int) -> Defs.ReanimDef:",
    TAB + "if not _defs.has(type):",
    TAB * 2 + "_defs[type] = Defs.load_reanim(files[type])",
    TAB + "return _defs[type]",
    "",
    "static func type_from_file(path: String) -> int:",
    TAB + "if _by_file.is_empty():",
    TAB * 2 + "for i in files.size():",
    TAB * 3 + "_by_file[files[i].to_lower()] = i",
    TAB + 'return _by_file.get(path.replace("' + BS + BS + '", "/").to_lower(), -1)',
    "",
    "## Registers a new reanim file (for custom content) and returns its type id.",
    "static func register(path: String) -> int:",
    TAB + "var t := type_from_file(path)",
    TAB + "if t != -1:",
    TAB * 2 + "return t",
    TAB + "files.append(path)",
    TAB + "_by_file[path.to_lower()] = files.size() - 1",
    TAB + "return files.size() - 1",
    "",
]
(ROOT / "src/core/reanim_types.gd").write_text("\n".join(out), encoding="utf-8")

out = ["# AUTO-GENERATED by tools/gen_type_tables.py", "class_name ParticleTypes", "",
       "## Index = PvZ.PARTICLE_* value.", "static var files: PackedStringArray = PackedStringArray(["]
for name, f in parts:
    out.append(TAB + '"particles/' + clean(f) + '",  # ' + name)
out += [
    "])",
    "static var _defs: Dictionary = {}",
    "",
    "static func get_def(effect: int) -> Defs.ParticleDef:",
    TAB + "if not _defs.has(effect):",
    TAB * 2 + "_defs[effect] = Defs.load_particle(files[effect])",
    TAB + "return _defs[effect]",
    "",
    "static func register(path: String) -> int:",
    TAB + "files.append(path)",
    TAB + "return files.size() - 1",
    "",
]
(ROOT / "src/core/particle_types.gd").write_text("\n".join(out), encoding="utf-8")
print(len(reanims), "reanims", len(parts), "particles")
